config/routes.rb
Rails.application.routes.draw do
  resources :workers, only: %i[show index new create edit update]
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'workers#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
  belongs_to :worker
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
    has_one :beneficiary

    accepts_nested_attributes_for :beneficiary


    mount_uploader :avatar, AvatarUploader
    mount_uploader :proof_address, ProofAddressUploader
    mount_uploader :banorte_contract, BanorteContractUploader
    mount_uploader :imss_discharge_notice, ImssDischargeNoticeUploader
    mount_uploader :infonavit_retention_notice, InfonavitRetentionNoticeUploader
    mount_uploader :work_contract, WorkContractUploader
    mount_uploaders :identification, IdentificationUploader
    mount_uploader :imss_format, ImssFormatUploader

    def self.search(search)
        if search
            Worker.where("nombre_completo LIKE :query", query: "%#{sanitize_sql_like(search.capitalize())}%")
        else
            Worker.all
        end

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:edit, :update, :show]
  before_action :authenticate_user!

  def show; end

  def index
    @workers = Worker.search(params[:search])
  end

  def new
    @worker = Worker.new
    @worker.build_beneficiary
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      redirect_to workers_path
    else
      render 'new'
    end
  end

  def edit ;end

  def update
    if @worker.update(worker_params)
      redirect_to workers_path
    else
      render 'edit'
    end
  end

  private 

  def set_worker
    @worker = Worker.find(params[:id])
  end

  def worker_params
    params.require(:worker).permit(
      :proof_address, :nombre_completo, :nss, :rfc, :curp, 
      :tel, :fecha_nacimiento, :fecha_ingreso, :sdi, 
      :sd, :sex, :job, :avatar, {identification: []},
      :banorte_contract, :email,:imss_discharge_notice, 
      :work_contract, :status,:infonavit_retention_notice, 
      :imss_format, :marital_status, :employee_number, :cel,
      :street, :outdoor_number, :interior_number, :search,
      :town, :cp, beneficiary_attributes: [ 
        :nombre_completo, :parentesco, :fecha_nacimiento,
        :street, :outdoor_number, :interior_number, :town,
        :cp
      ]
    )
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
    <div class="container container-fluid">
        <%= link_to authenticated_root_path, class: "navbar-brand font-weight-bold"  do %>
            Air Supply <%= fa_icon "industry"%>
        <% end %>

        <div class="navbar-text pull-right">
            <%= link_to destroy_user_session_path, class: "navbar-link", method: :delete do %>
                Cerrar Sesion <%= fa_icon "sign-out"%>
            <% end %>

        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirSupply</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' if user_signed_in? %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/workers/_worker_form.html.erb
<div class="worker-form container">
    <div class="header">
        <%= button_to "Regresar", workers_path, method: :get ,class: "btn btn-success"%>
    </div>
    <%= form_for(@worker, url: {action: action_type}) do |worker_form|%>
        <h2>Informacion de Trabajador</h2>
        <div class="form-group">
            <%= worker_form.label :nombre_completo, 'Nombre Completo'%><br>
            <%= worker_form.text_field :nombre_completo, required: true, class: "form-control", placeholder: "Nombre Completo" %>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :nss, "NSS" %><br>
                <%= worker_form.text_field :nss, required: true, class: "form-control", placeholder: "NSS" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :rfc, "RFC" %><br>
                <%= worker_form.text_field :rfc, required: true, class: "form-control", placeholder: "RFC" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :curp, "CURP" %><br>
                <%= worker_form.text_field :curp, required: true, class: "form-control", placeholder: "CURP" %>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :tel, "Telefono" %><br>
                <%= worker_form.text_field :tel, required: true, class: "form-control", placeholder: "Telefono" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :cel, "Celular" %><br>
                <%= worker_form.text_field :cel, required: true, class: "form-control", placeholder: "Celular" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :fecha_nacimiento, "Fecha de Nacimiento" %><br>
                <%= worker_form.date_field :fecha_nacimiento, required: true, class: "form-control" %>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :sex, "Sexo" %><br>
                <%= worker_form.select :sex, ['Masculino' , 'Feminino'], { include_blank: "Seleccionar", required: true }, { class: "form-control" } %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :marital_status, "Estado Civil" %><br>
                <%= worker_form.select :marital_status, ["Solter@", "Casad@"], { include_blank: "Seleccionar", required: true }, { class: "form-control" } %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :email, "Correo" %><br>
                <%= worker_form.email_field :email, required: true, class: "form-control", placeholder: "Correo" %>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :fecha_ingreso, "Fecha Ingreso" %><br>
                <%= worker_form.date_field :fecha_ingreso, required: true, class: "form-control" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :sdi, "SDI" %><br>
                <%= worker_form.number_field :sdi, required: true, class: "form-control", placeholder: "SDI" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :sd, "SD" %><br>
                <%= worker_form.number_field :sd, required: true, class: "form-control", placeholder: "SD" %>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :employee_number, "Numero de Empleado" %><br>
                <%= worker_form.text_field :employee_number, required: true, class: "form-control", placeholder: "Numero de Empleado" %>
            </div>
        </div>

        <h2>Direccion</h2>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :street, "Calle" %>
                <%= worker_form.text_field :street, required: true, class: "form-control", placeholder: "Calle" %>
            </div> 
            <div class="form-group col-md-4">
                <%= worker_form.label :outdoor_number, "Numero Exterior" %>
                <%= worker_form.text_field :outdoor_number, required: true, class: "form-control", placeholder: "Numero Exterior" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :interior_number, "Numer Interior" %>
                <%= worker_form.text_field :interior_number, class: "form-control", placeholder: "Numero Interior" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :town, "Ciudad/Municipio" %>
                <%= worker_form.text_field :town, required: true, class: "form-control", placeholder: "Ciudad/Municipio" %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :cp, "Codigo Postal" %>
                <%= worker_form.text_field :cp, required: true, class: "form-control", placeholder: "Codigo Postal" %>
            </div>
        </div>

        <h2>Datos de Beneficiario</h2>
        <%= worker_form.fields_for :beneficiary do |beneficiary_form| %>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :nombre_completo, "Nombre completo" %>
                    <%= beneficiary_form.text_field :nombre_completo, required: true, class: "form-control", placeholder: "Nombre Completo" %>
                </div>
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :parentesco, "Parentesco" %>
                    <%= beneficiary_form.text_field :parentesco, required: true, class: "form-control", placeholder: "Parentesco" %>
                </div>
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :fecha_nacimiento, "Fecha Nacimiento" %>
                    <%= beneficiary_form.date_field :fecha_nacimiento, required: true, class: "form-control" %>
                </div>
            </div>

            <h4>Direccion de Beneficiario</h4>
            <div class="form-row">
                
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :street, "Calle" %>
                    <%= beneficiary_form.text_field :street, required: true, class: "form-control", placeholder: "Calle" %>
                </div>
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :outdoor_number, "Numero Exterior" %>
                    <%= beneficiary_form.text_field :outdoor_number, required: true, class: "form-control", placeholder: "Numero Exterior" %>
                </div>
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :interior_number, "Numero Interior" %>
                    <%= beneficiary_form.text_field :interior_number, class: "form-control", placeholder: "Numero Interior" %>
                </div>
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :town, "Ciudad/Municipio" %>
                    <%= beneficiary_form.text_field :town, class: "form-control", placeholder: "Ciudad/Municipio" %>
                </div>
                <div class="form-group col-md-4">
                    <%= beneficiary_form.label :cp, "Codigo Postal" %>
                    <%= beneficiary_form.text_field :cp, class: "form-control", placeholder: "Codigo Postal" %>
                </div>
            </div>
        <% end %>

        <h2>Documentos</h2>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :avatar, "Foto de Trabajador" %><br>
                <%= image_tag(@worker.avatar_url, class: "card-img-top") if @worker.avatar?%>
                <%= worker_form.file_field :avatar, required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :avatar_cache %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :identification, "INE/IFE" %><br>
                <% @worker.identification_identifiers.each do |filename| %>
                    <%= filename %>
                <% end %>
                <%= worker_form.file_field :identification, multiple: true ,required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :identification_cache %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :proof_address, "Comprobante de Domicilio" %><br>
                <%= @worker.proof_address_identifier %>
                <%= worker_form.file_field :proof_address,required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :proof_address_cache %>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :banorte_contract, "Contrato Banorte" %><br>
                <%= @worker.banorte_contract_identifier %>
                <%= worker_form.file_field :banorte_contract, required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :banorte_contract_cache %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :work_contract, "Contrato Laboral" %><br>
                <%= @worker.work_contract_identifier %>
                <%= worker_form.file_field :work_contract ,required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :work_contract_cache %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :imss_format, "Formato de Alta IMSS" %><br>
                <%= @worker.imss_format_identifier %>
                <%= worker_form.file_field :imss_format, required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :imss_format_cache %>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <%= worker_form.label :imss_discharge_notice, "Aviso de Alta IMSS" %><br>
                <%= @worker.imss_discharge_notice_identifier %>
                <%= worker_form.file_field :imss_discharge_notice, required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :imss_discharge_notice_cache %>
            </div>
            <div class="form-group col-md-4">
                <%= worker_form.label :infonavit_retention_notice, "Aviso de Retención Infonavit" %><br>
                <%= @worker.infonavit_retention_notice_identifier %>
                <%= worker_form.file_field :infonavit_retention_notice ,required: (action_type == "create"), class: "form-control" %>
                <%= worker_form.hidden_field :infonavit_retention_notice_cache %>
            </div>
        </div>
        <%= worker_form.submit btn_message, class: "btn btn-success btn-lg submit-button"%>
    <% end %>
</div>

app/views/workers/edit.html.erb
<%= render partial: 'worker_form', locals: {action_type: "update", btn_message: "Actualizar Informacion"}%>

app/views/workers/index.html.erb
<div class="container workers">
    <div class="header">
        <h1>Trabajadores</h1>
        <%= button_to "Nuevo Trabajador", new_worker_path, method: :get ,class: "btn btn-success"%>
    </div>

    <%= form_tag(workers_path, method: :get, class: "form-inline mb-4") do %>
        <%= text_field_tag(:search, params[:search], placeholder: "Buscar Trabajador", class: "form-control col-sm-6 mx-sm-3") %>
        <%= submit_tag("Buscar", nombre_completo: nil, class: "btn btn-primary")%>
    <% end %>

    <div class="row">
        <% @workers.each do |worker| %>
            <div class="col-md-4">
                <div class="card mb-3 shadow-sm">
                    <div class="embed-responsive embed-responsive-4by3">
                        <%= image_tag(worker.avatar_url, class: "card-img-top embed-responsive-item", alt: "Imagen Trabajador") %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title font-weight-bold"><%= worker.nombre_completo %></h5>
                        <p class="card-text">
                            NSS: <%= worker.nss %> <br>
                            RFC: <%= worker.rfc %> <br>
                            CURP: <%= worker.curp %> <br>
                        </p>
                        <%= button_to "Mas Informacion", worker, method: :get, class: "btn btn-primary"%>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/workers/new.html.erb
<%= render partial: 'worker_form', locals: {action_type: "create", btn_message: "Dar de Alta"}%>

app/views/workers/show.html.erb
<div class="container worker">
    <div class="header">
        <%= button_to "Regresar", workers_path, method: :get ,class: "btn btn-success"%>
    </div>
    <h2><%= @worker.nombre_completo %></h2>
</div>